### ISSUE TITLE
Replace HTTP server for Github comments webhook

### ISSUE THREAD

**Issue by izqui** [aragon/autobounty#1]
Migrated from https://github.com/aragon/aragon-core/issues/8

**Comment by commiteth** [comment]
Balance: 0.0000
Contract address: 0x19d8acac27553ef390d287b532bbc1f9fdcc261c
Network: Mainnet
Status: pending maintainer confirmation
Winner: snugghash

**Comment by izqui** [comment]
cc @snugghash

**Comment by snugghash** [comment]
So I implemented this without really interacting with the Github bot API, this is just a listener that consumes POST requests from a `issue_comment` webhook, parses the addresses and amounts, and tries the transaction. 
Submitting PR now, please review, feel free to suggest edits / edit to your liking.

**Comment by izqui** [comment]
Regarding bounties for this repo, let's wait to have autobounty up and running and we can dogfood it here :)
